bot:
  token: <INSERT API TOKEN OF YOUR TELEGRAM BOT>
  username: <INSERT USERNAME OF YOU BOT>

user:
  tg_id: <INSERT YOUR TELEGRAM USER ID>

complice:
  auth_token: <INSERT YOUR COMPLICE API TOKEN>
